name: home
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.1.1
  firebase_auth: ^5.1.0

  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+1

  flutter_dotenv: ^5.0.2

  # Google APIs (Gmail)
  googleapis: ^13.0.0  # Updated for better compatibility
  googleapis_auth: ^1.4.1  # Aligned with googleapis

  # Vertex AI & Gemini
  firebase_vertexai: ^0.2.2+1

  cupertino_icons: ^1.0.6
  html: ^0.15.0
  audioplayers: ^6.0.0
  http: ^1.2.1
  dropdown_search: ^5.0.2
  timeline_tile: ^2.0.0
  path_provider: ^2.0.15
  flutter_spinkit: ^5.1.0
  animations: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  shimmer: ^2.0.0
  flutter_speed_dial: ^6.2.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  url_launcher: ^6.2.5
  just_audio: ^0.9.34

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.2.3
  build_runner: ^2.4.6

flutter:
  assets:
    - assets/.env
    - assets/audio/Josephv2.mp3
    - assets/audio/buildspace_w1.mp3
    - assets/audio/buildspace_w2.mp3
    - assets/audio/buildspace_w3.mp3
    - assets/audio/default.mp3
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
