name: home
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+1

  flutter_dotenv: ^5.0.2

  # Google APIs (Gmail)
  googleapis: ^13.0.0  # Updated for better compatibility
  googleapis_auth: ^1.4.1  # Aligned with googleapis

  cupertino_icons: ^1.0.6
  html: ^0.15.0
  audioplayers: ^6.0.0
  http: ^1.2.1
  dropdown_search: ^5.0.2
  timeline_tile: ^2.0.0
  path_provider: ^2.0.15
  flutter_spinkit: ^5.1.0
  animations: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  shimmer: ^2.0.0
  flutter_speed_dial: ^6.2.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  url_launcher: ^6.3.0  # Use the latest version available
  just_audio: ^0.9.34
  m3_carousel: ^1.0.0
  firebase_vertexai: ^0.1.1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  firebase_analytics: ^10.8.5
  intl: ^0.18.0
  webview_flutter: ^4.4.2  # Use the latest version available
  js: ^0.6.3  # Add this line if it's not already present
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1 
  image: ^3.0.2
  xml: ^6.3.0
  dio: ^5.0.0
  file_picker: ^5.0.0
  crypto: ^3.0.2
  permission_handler: ^10.0.0

  # Add these new dependencies
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.2.3
  build_runner: ^2.4.6

flutter:
  assets:
    - assets/.env
    - assets/audio/
  uses-material-design: true